/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AccountUsageStatisticsInterval.h
 *
 * Data interval
 */

#ifndef IO_TRADEWATCH_CLIENT_MODEL_AccountUsageStatisticsInterval_H_
#define IO_TRADEWATCH_CLIENT_MODEL_AccountUsageStatisticsInterval_H_


#include "Tradewatch/ModelBase.h"


namespace io {
namespace tradewatch {
namespace client {
namespace model {


class  AccountUsageStatisticsInterval
    : public ModelBase
{
public:
    AccountUsageStatisticsInterval();
    virtual ~AccountUsageStatisticsInterval();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eAccountUsageStatisticsInterval
    {
        AccountUsageStatisticsInterval__1H,
        AccountUsageStatisticsInterval__1D,
    };

    eAccountUsageStatisticsInterval getValue() const;
    void setValue(eAccountUsageStatisticsInterval const value);

    protected:
        eAccountUsageStatisticsInterval m_value;
};

}
}
}
}

#endif /* IO_TRADEWATCH_CLIENT_MODEL_AccountUsageStatisticsInterval_H_ */
