/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ApiUsageEntry.h
 *
 * Usage history entry
 */

#ifndef IO_TRADEWATCH_CLIENT_MODEL_ApiUsageEntry_H_
#define IO_TRADEWATCH_CLIENT_MODEL_ApiUsageEntry_H_


#include "Tradewatch/ModelBase.h"

#include "Tradewatch/model/ApiUsageDataTransfer.h"

namespace io {
namespace tradewatch {
namespace client {
namespace model {

class ApiUsageDataTransfer;


/// <summary>
/// Usage history entry
/// </summary>
class  ApiUsageEntry
    : public ModelBase
{
public:
    ApiUsageEntry();
    virtual ~ApiUsageEntry();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ApiUsageEntry members

    /// <summary>
    /// 
    /// </summary>
    int32_t getRequests() const;
    bool requestsIsSet() const;
    void unsetRequests();

    void setRequests(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ApiUsageDataTransfer> getData() const;
    bool dataIsSet() const;
    void unsetData();

    void setData(const std::shared_ptr<ApiUsageDataTransfer>& value);


protected:
    int32_t m_Requests;
    bool m_RequestsIsSet;
    std::shared_ptr<ApiUsageDataTransfer> m_Data;
    bool m_DataIsSet;
};


}
}
}
}

#endif /* IO_TRADEWATCH_CLIENT_MODEL_ApiUsageEntry_H_ */
