/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ApiUsageDataTransfer.h
 *
 * Data transfer
 */

#ifndef IO_TRADEWATCH_CLIENT_MODEL_ApiUsageDataTransfer_H_
#define IO_TRADEWATCH_CLIENT_MODEL_ApiUsageDataTransfer_H_


#include "Tradewatch/ModelBase.h"


namespace io {
namespace tradewatch {
namespace client {
namespace model {



/// <summary>
/// Data transfer
/// </summary>
class  ApiUsageDataTransfer
    : public ModelBase
{
public:
    ApiUsageDataTransfer();
    virtual ~ApiUsageDataTransfer();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ApiUsageDataTransfer members

    /// <summary>
    /// 
    /// </summary>
    int32_t getRequest() const;
    bool requestIsSet() const;
    void unsetRequest();

    void setRequest(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getResponse() const;
    bool responseIsSet() const;
    void unsetResponse();

    void setResponse(int32_t value);


protected:
    int32_t m_Request;
    bool m_RequestIsSet;
    int32_t m_Response;
    bool m_ResponseIsSet;
};


}
}
}
}

#endif /* IO_TRADEWATCH_CLIENT_MODEL_ApiUsageDataTransfer_H_ */
