/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CommodityTypesList.h
 *
 * A list of commodity types
 */

#ifndef IO_TRADEWATCH_CLIENT_MODEL_CommodityTypesList_H_
#define IO_TRADEWATCH_CLIENT_MODEL_CommodityTypesList_H_


#include "Tradewatch/ModelBase.h"

#include "Tradewatch/model/CommodityTypeObj.h"
#include <vector>

namespace io {
namespace tradewatch {
namespace client {
namespace model {

class CommodityTypeObj;


/// <summary>
/// A list of commodity types
/// </summary>
class  CommodityTypesList
    : public ModelBase
{
public:
    CommodityTypesList();
    virtual ~CommodityTypesList();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CommodityTypesList members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<CommodityTypeObj>>& getItems();
    bool itemsIsSet() const;
    void unsetItems();

    void setItems(const std::vector<std::shared_ptr<CommodityTypeObj>>& value);


protected:
    std::vector<std::shared_ptr<CommodityTypeObj>> m_Items;
    bool m_ItemsIsSet;
};


}
}
}
}

#endif /* IO_TRADEWATCH_CLIENT_MODEL_CommodityTypesList_H_ */
