/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ConversionQuery.h
 *
 * 
 */

#ifndef IO_TRADEWATCH_CLIENT_MODEL_ConversionQuery_H_
#define IO_TRADEWATCH_CLIENT_MODEL_ConversionQuery_H_


#include "Tradewatch/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace tradewatch {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  ConversionQuery
    : public ModelBase
{
public:
    ConversionQuery();
    virtual ~ConversionQuery();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ConversionQuery members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getFrom() const;
    bool fromIsSet() const;
    void unsetFrom();

    void setFrom(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getTo() const;
    bool toIsSet() const;
    void unsetTo();

    void setTo(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    double getAmount() const;
    bool amountIsSet() const;
    void unsetAmount();

    void setAmount(double value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getPrecision() const;
    bool precisionIsSet() const;
    void unsetPrecision();

    void setPrecision(int32_t value);


protected:
    utility::string_t m_From;
    bool m_FromIsSet;
    utility::string_t m_To;
    bool m_ToIsSet;
    double m_Amount;
    bool m_AmountIsSet;
    int32_t m_Precision;
    bool m_PrecisionIsSet;
};


}
}
}
}

#endif /* IO_TRADEWATCH_CLIENT_MODEL_ConversionQuery_H_ */
