/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ConversionInfo.h
 *
 * 
 */

#ifndef IO_TRADEWATCH_CLIENT_MODEL_ConversionInfo_H_
#define IO_TRADEWATCH_CLIENT_MODEL_ConversionInfo_H_


#include "Tradewatch/ModelBase.h"


namespace io {
namespace tradewatch {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  ConversionInfo
    : public ModelBase
{
public:
    ConversionInfo();
    virtual ~ConversionInfo();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ConversionInfo members

    /// <summary>
    /// 
    /// </summary>
    int32_t getTimestamp() const;
    bool timestampIsSet() const;
    void unsetTimestamp();

    void setTimestamp(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    double getRate() const;
    bool rateIsSet() const;
    void unsetRate();

    void setRate(double value);


protected:
    int32_t m_Timestamp;
    bool m_TimestampIsSet;
    double m_Rate;
    bool m_RateIsSet;
};


}
}
}
}

#endif /* IO_TRADEWATCH_CLIENT_MODEL_ConversionInfo_H_ */
