/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Country.h
 *
 * The country associated with the symbol (see ISO 3166-1 alpha-2)
 */

#ifndef IO_TRADEWATCH_CLIENT_MODEL_Country_H_
#define IO_TRADEWATCH_CLIENT_MODEL_Country_H_


#include "Tradewatch/ModelBase.h"


namespace io {
namespace tradewatch {
namespace client {
namespace model {


class  Country
    : public ModelBase
{
public:
    Country();
    virtual ~Country();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eCountry
    {
        Country_FR,
        Country_US,
        Country_DE,
        Country_NZ,
        Country_NL,
        Country_UK,
        Country_ES,
        Country_CN,
        Country_CH,
        Country_GR,
        Country_BE,
        Country_PT,
        Country_IT,
        Country_ALL,
    };

    eCountry getValue() const;
    void setValue(eCountry const value);

    protected:
        eCountry m_value;
};

}
}
}
}

#endif /* IO_TRADEWATCH_CLIENT_MODEL_Country_H_ */
