/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * HTTPValidationError.h
 *
 * 
 */

#ifndef IO_TRADEWATCH_CLIENT_MODEL_HTTPValidationError_H_
#define IO_TRADEWATCH_CLIENT_MODEL_HTTPValidationError_H_


#include "Tradewatch/ModelBase.h"

#include "Tradewatch/model/ValidationError.h"
#include <vector>

namespace io {
namespace tradewatch {
namespace client {
namespace model {

class ValidationError;


/// <summary>
/// 
/// </summary>
class  HTTPValidationError
    : public ModelBase
{
public:
    HTTPValidationError();
    virtual ~HTTPValidationError();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// HTTPValidationError members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<ValidationError>>& getDetail();
    bool detailIsSet() const;
    void unsetDetail();

    void setDetail(const std::vector<std::shared_ptr<ValidationError>>& value);


protected:
    std::vector<std::shared_ptr<ValidationError>> m_Detail;
    bool m_DetailIsSet;
};


}
}
}
}

#endif /* IO_TRADEWATCH_CLIENT_MODEL_HTTPValidationError_H_ */
