/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "Tradewatch/model/ApiUsageEntry.h"

namespace io {
namespace tradewatch {
namespace client {
namespace model {



ApiUsageEntry::ApiUsageEntry()
{
    m_Requests = 0;
    m_RequestsIsSet = false;
    m_DataIsSet = false;
}

ApiUsageEntry::~ApiUsageEntry()
{
}

void ApiUsageEntry::validate()
{
    // TODO: implement validation
}

web::json::value ApiUsageEntry::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_RequestsIsSet)
    {
        val[utility::conversions::to_string_t(U("requests"))] = ModelBase::toJson(m_Requests);
    }
    if(m_DataIsSet)
    {
        val[utility::conversions::to_string_t(U("data"))] = ModelBase::toJson(m_Data);
    }

    return val;
}

bool ApiUsageEntry::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("requests"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("requests")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setRequests;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRequests);
            setRequests(refVal_setRequests);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("data"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("data")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ApiUsageDataTransfer> refVal_setData;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData);
            setData(refVal_setData);
        }
    }
    return ok;
}

void ApiUsageEntry::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_RequestsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("requests")), m_Requests));
    }
    if(m_DataIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("data")), m_Data));
    }
}

bool ApiUsageEntry::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("requests"))))
    {
        int32_t refVal_setRequests;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("requests"))), refVal_setRequests );
        setRequests(refVal_setRequests);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("data"))))
    {
        std::shared_ptr<ApiUsageDataTransfer> refVal_setData;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("data"))), refVal_setData );
        setData(refVal_setData);
    }
    return ok;
}

int32_t ApiUsageEntry::getRequests() const
{
    return m_Requests;
}

void ApiUsageEntry::setRequests(int32_t value)
{
    m_Requests = value;
    m_RequestsIsSet = true;
}

bool ApiUsageEntry::requestsIsSet() const
{
    return m_RequestsIsSet;
}

void ApiUsageEntry::unsetRequests()
{
    m_RequestsIsSet = false;
}
std::shared_ptr<ApiUsageDataTransfer> ApiUsageEntry::getData() const
{
    return m_Data;
}

void ApiUsageEntry::setData(const std::shared_ptr<ApiUsageDataTransfer>& value)
{
    m_Data = value;
    m_DataIsSet = true;
}

bool ApiUsageEntry::dataIsSet() const
{
    return m_DataIsSet;
}

void ApiUsageEntry::unsetData()
{
    m_DataIsSet = false;
}
}
}
}
}


