/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "Tradewatch/model/ApiUsageDataTransfer.h"

namespace io {
namespace tradewatch {
namespace client {
namespace model {



ApiUsageDataTransfer::ApiUsageDataTransfer()
{
    m_Request = 0;
    m_RequestIsSet = false;
    m_Response = 0;
    m_ResponseIsSet = false;
}

ApiUsageDataTransfer::~ApiUsageDataTransfer()
{
}

void ApiUsageDataTransfer::validate()
{
    // TODO: implement validation
}

web::json::value ApiUsageDataTransfer::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_RequestIsSet)
    {
        val[utility::conversions::to_string_t(U("request"))] = ModelBase::toJson(m_Request);
    }
    if(m_ResponseIsSet)
    {
        val[utility::conversions::to_string_t(U("response"))] = ModelBase::toJson(m_Response);
    }

    return val;
}

bool ApiUsageDataTransfer::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("request"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("request")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setRequest;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRequest);
            setRequest(refVal_setRequest);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("response"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("response")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setResponse;
            ok &= ModelBase::fromJson(fieldValue, refVal_setResponse);
            setResponse(refVal_setResponse);
        }
    }
    return ok;
}

void ApiUsageDataTransfer::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_RequestIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("request")), m_Request));
    }
    if(m_ResponseIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("response")), m_Response));
    }
}

bool ApiUsageDataTransfer::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("request"))))
    {
        int32_t refVal_setRequest;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("request"))), refVal_setRequest );
        setRequest(refVal_setRequest);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("response"))))
    {
        int32_t refVal_setResponse;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("response"))), refVal_setResponse );
        setResponse(refVal_setResponse);
    }
    return ok;
}

int32_t ApiUsageDataTransfer::getRequest() const
{
    return m_Request;
}

void ApiUsageDataTransfer::setRequest(int32_t value)
{
    m_Request = value;
    m_RequestIsSet = true;
}

bool ApiUsageDataTransfer::requestIsSet() const
{
    return m_RequestIsSet;
}

void ApiUsageDataTransfer::unsetRequest()
{
    m_RequestIsSet = false;
}
int32_t ApiUsageDataTransfer::getResponse() const
{
    return m_Response;
}

void ApiUsageDataTransfer::setResponse(int32_t value)
{
    m_Response = value;
    m_ResponseIsSet = true;
}

bool ApiUsageDataTransfer::responseIsSet() const
{
    return m_ResponseIsSet;
}

void ApiUsageDataTransfer::unsetResponse()
{
    m_ResponseIsSet = false;
}
}
}
}
}


