/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.9.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "Tradewatch/model/CommodityType.h"

namespace io {
namespace tradewatch {
namespace client {
namespace model {


namespace
{
using EnumUnderlyingType = utility::string_t;

CommodityType::eCommodityType toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("agricultural")))
        return CommodityType::eCommodityType::CommodityType_AGRICULTURAL;
    if (val == utility::conversions::to_string_t(U("energy")))
        return CommodityType::eCommodityType::CommodityType_ENERGY;
    if (val == utility::conversions::to_string_t(U("metal")))
        return CommodityType::eCommodityType::CommodityType_METAL;
    if (val == utility::conversions::to_string_t(U("all")))
        return CommodityType::eCommodityType::CommodityType_ALL;
    return {};
}

EnumUnderlyingType fromEnum(CommodityType::eCommodityType e)
{
    switch (e)
    {
    case CommodityType::eCommodityType::CommodityType_AGRICULTURAL:
        return U("agricultural");
    case CommodityType::eCommodityType::CommodityType_ENERGY:
        return U("energy");
    case CommodityType::eCommodityType::CommodityType_METAL:
        return U("metal");
    case CommodityType::eCommodityType::CommodityType_ALL:
        return U("all");
    default:
        break;
    }
    return {};
}
}

CommodityType::CommodityType()
{
}

CommodityType::~CommodityType()
{
}

void CommodityType::validate()
{
    // TODO: implement validation
}

web::json::value CommodityType::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool CommodityType::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void CommodityType::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool CommodityType::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

CommodityType::eCommodityType CommodityType::getValue() const
{
   return m_value;
}

void CommodityType::setValue(CommodityType::eCommodityType const value)
{
   m_value = value;
}


}
}
}
}


