/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "Tradewatch/model/CryptoExchangeItem.h"

namespace io {
namespace tradewatch {
namespace client {
namespace model {



CryptoExchangeItem::CryptoExchangeItem()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Year_established = 0;
    m_Year_establishedIsSet = false;
}

CryptoExchangeItem::~CryptoExchangeItem()
{
}

void CryptoExchangeItem::validate()
{
    // TODO: implement validation
}

web::json::value CryptoExchangeItem::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t(U("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_Year_establishedIsSet)
    {
        val[utility::conversions::to_string_t(U("year_established"))] = ModelBase::toJson(m_Year_established);
    }

    return val;
}

bool CryptoExchangeItem::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("year_established"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("year_established")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setYearEstablished;
            ok &= ModelBase::fromJson(fieldValue, refVal_setYearEstablished);
            setYearEstablished(refVal_setYearEstablished);
        }
    }
    return ok;
}

void CryptoExchangeItem::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
    }
    if(m_Year_establishedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("year_established")), m_Year_established));
    }
}

bool CryptoExchangeItem::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("year_established"))))
    {
        int32_t refVal_setYearEstablished;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("year_established"))), refVal_setYearEstablished );
        setYearEstablished(refVal_setYearEstablished);
    }
    return ok;
}

utility::string_t CryptoExchangeItem::getId() const
{
    return m_Id;
}

void CryptoExchangeItem::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool CryptoExchangeItem::idIsSet() const
{
    return m_IdIsSet;
}

void CryptoExchangeItem::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t CryptoExchangeItem::getName() const
{
    return m_Name;
}

void CryptoExchangeItem::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool CryptoExchangeItem::nameIsSet() const
{
    return m_NameIsSet;
}

void CryptoExchangeItem::unsetName()
{
    m_NameIsSet = false;
}
int32_t CryptoExchangeItem::getYearEstablished() const
{
    return m_Year_established;
}

void CryptoExchangeItem::setYearEstablished(int32_t value)
{
    m_Year_established = value;
    m_Year_establishedIsSet = true;
}

bool CryptoExchangeItem::yearEstablishedIsSet() const
{
    return m_Year_establishedIsSet;
}

void CryptoExchangeItem::unsetYear_established()
{
    m_Year_establishedIsSet = false;
}
}
}
}
}


