/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "Tradewatch/model/CryptoConversionQuery.h"

namespace io {
namespace tradewatch {
namespace client {
namespace model {



CryptoConversionQuery::CryptoConversionQuery()
{
    m_From = utility::conversions::to_string_t("");
    m_FromIsSet = false;
    m_To = utility::conversions::to_string_t("");
    m_ToIsSet = false;
    m_Amount = 0.0;
    m_AmountIsSet = false;
    m_Precision = 0;
    m_PrecisionIsSet = false;
}

CryptoConversionQuery::~CryptoConversionQuery()
{
}

void CryptoConversionQuery::validate()
{
    // TODO: implement validation
}

web::json::value CryptoConversionQuery::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_FromIsSet)
    {
        val[utility::conversions::to_string_t(U("from"))] = ModelBase::toJson(m_From);
    }
    if(m_ToIsSet)
    {
        val[utility::conversions::to_string_t(U("to"))] = ModelBase::toJson(m_To);
    }
    if(m_AmountIsSet)
    {
        val[utility::conversions::to_string_t(U("amount"))] = ModelBase::toJson(m_Amount);
    }
    if(m_PrecisionIsSet)
    {
        val[utility::conversions::to_string_t(U("precision"))] = ModelBase::toJson(m_Precision);
    }

    return val;
}

bool CryptoConversionQuery::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("from"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("from")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFrom;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFrom);
            setFrom(refVal_setFrom);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("to"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("to")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTo;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTo);
            setTo(refVal_setTo);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("amount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("amount")));
        if(!fieldValue.is_null())
        {
            double refVal_setAmount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAmount);
            setAmount(refVal_setAmount);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("precision"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("precision")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPrecision;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPrecision);
            setPrecision(refVal_setPrecision);
        }
    }
    return ok;
}

void CryptoConversionQuery::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_FromIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("from")), m_From));
    }
    if(m_ToIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("to")), m_To));
    }
    if(m_AmountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("amount")), m_Amount));
    }
    if(m_PrecisionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("precision")), m_Precision));
    }
}

bool CryptoConversionQuery::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("from"))))
    {
        utility::string_t refVal_setFrom;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("from"))), refVal_setFrom );
        setFrom(refVal_setFrom);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("to"))))
    {
        utility::string_t refVal_setTo;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("to"))), refVal_setTo );
        setTo(refVal_setTo);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("amount"))))
    {
        double refVal_setAmount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("amount"))), refVal_setAmount );
        setAmount(refVal_setAmount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("precision"))))
    {
        int32_t refVal_setPrecision;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("precision"))), refVal_setPrecision );
        setPrecision(refVal_setPrecision);
    }
    return ok;
}

utility::string_t CryptoConversionQuery::getFrom() const
{
    return m_From;
}

void CryptoConversionQuery::setFrom(const utility::string_t& value)
{
    m_From = value;
    m_FromIsSet = true;
}

bool CryptoConversionQuery::fromIsSet() const
{
    return m_FromIsSet;
}

void CryptoConversionQuery::unsetFrom()
{
    m_FromIsSet = false;
}
utility::string_t CryptoConversionQuery::getTo() const
{
    return m_To;
}

void CryptoConversionQuery::setTo(const utility::string_t& value)
{
    m_To = value;
    m_ToIsSet = true;
}

bool CryptoConversionQuery::toIsSet() const
{
    return m_ToIsSet;
}

void CryptoConversionQuery::unsetTo()
{
    m_ToIsSet = false;
}
double CryptoConversionQuery::getAmount() const
{
    return m_Amount;
}

void CryptoConversionQuery::setAmount(double value)
{
    m_Amount = value;
    m_AmountIsSet = true;
}

bool CryptoConversionQuery::amountIsSet() const
{
    return m_AmountIsSet;
}

void CryptoConversionQuery::unsetAmount()
{
    m_AmountIsSet = false;
}
int32_t CryptoConversionQuery::getPrecision() const
{
    return m_Precision;
}

void CryptoConversionQuery::setPrecision(int32_t value)
{
    m_Precision = value;
    m_PrecisionIsSet = true;
}

bool CryptoConversionQuery::precisionIsSet() const
{
    return m_PrecisionIsSet;
}

void CryptoConversionQuery::unsetPrecision()
{
    m_PrecisionIsSet = false;
}
}
}
}
}


