/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "Tradewatch/model/ValidationError.h"

namespace io {
namespace tradewatch {
namespace client {
namespace model {



ValidationError::ValidationError()
{
    m_LocIsSet = false;
    m_Msg = utility::conversions::to_string_t("");
    m_MsgIsSet = false;
    m_Type = utility::conversions::to_string_t("");
    m_TypeIsSet = false;
}

ValidationError::~ValidationError()
{
}

void ValidationError::validate()
{
    // TODO: implement validation
}

web::json::value ValidationError::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_LocIsSet)
    {
        val[utility::conversions::to_string_t(U("loc"))] = ModelBase::toJson(m_Loc);
    }
    if(m_MsgIsSet)
    {
        val[utility::conversions::to_string_t(U("msg"))] = ModelBase::toJson(m_Msg);
    }
    if(m_TypeIsSet)
    {
        val[utility::conversions::to_string_t(U("type"))] = ModelBase::toJson(m_Type);
    }

    return val;
}

bool ValidationError::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("loc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("loc")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<ValidationError_loc_inner>> refVal_setLoc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLoc);
            setLoc(refVal_setLoc);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("msg"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("msg")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMsg;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMsg);
            setMsg(refVal_setMsg);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setType);
            setType(refVal_setType);
        }
    }
    return ok;
}

void ValidationError::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_LocIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("loc")), m_Loc));
    }
    if(m_MsgIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("msg")), m_Msg));
    }
    if(m_TypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("type")), m_Type));
    }
}

bool ValidationError::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("loc"))))
    {
        std::vector<std::shared_ptr<ValidationError_loc_inner>> refVal_setLoc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("loc"))), refVal_setLoc );
        setLoc(refVal_setLoc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("msg"))))
    {
        utility::string_t refVal_setMsg;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("msg"))), refVal_setMsg );
        setMsg(refVal_setMsg);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("type"))))
    {
        utility::string_t refVal_setType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("type"))), refVal_setType );
        setType(refVal_setType);
    }
    return ok;
}

std::vector<std::shared_ptr<ValidationError_loc_inner>>& ValidationError::getLoc()
{
    return m_Loc;
}

void ValidationError::setLoc(const std::vector<std::shared_ptr<ValidationError_loc_inner>>& value)
{
    m_Loc = value;
    m_LocIsSet = true;
}

bool ValidationError::locIsSet() const
{
    return m_LocIsSet;
}

void ValidationError::unsetLoc()
{
    m_LocIsSet = false;
}
utility::string_t ValidationError::getMsg() const
{
    return m_Msg;
}

void ValidationError::setMsg(const utility::string_t& value)
{
    m_Msg = value;
    m_MsgIsSet = true;
}

bool ValidationError::msgIsSet() const
{
    return m_MsgIsSet;
}

void ValidationError::unsetMsg()
{
    m_MsgIsSet = false;
}
utility::string_t ValidationError::getType() const
{
    return m_Type;
}

void ValidationError::setType(const utility::string_t& value)
{
    m_Type = value;
    m_TypeIsSet = true;
}

bool ValidationError::typeIsSet() const
{
    return m_TypeIsSet;
}

void ValidationError::unsetType()
{
    m_TypeIsSet = false;
}
}
}
}
}


