/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AnyType.h
 *
 * This is the implementation of an any JSON type.
 */

#ifndef IO_TRADEWATCH_CLIENT_MODEL_AnyType_H_
#define IO_TRADEWATCH_CLIENT_MODEL_AnyType_H_


#include "Tradewatch/Object.h"

#include <cpprest/details/basic_types.h>
#include <cpprest/json.h>

namespace io {
namespace tradewatch {
namespace client {
namespace model {

class  AnyType : public Object {
public:
  AnyType();
  virtual ~AnyType();

  /////////////////////////////////////////////
  /// ModelBase overrides
  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

private:
  web::json::value m_value;
};

}
}
}
}

#endif /* IO_TRADEWATCH_CLIENT_MODEL_AnyType_H_ */
