/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * JsonBody.h
 *
 * This is a JSON http body which can be submitted via http
 */

#ifndef IO_TRADEWATCH_CLIENT_MODEL_JsonBody_H_
#define IO_TRADEWATCH_CLIENT_MODEL_JsonBody_H_


#include "Tradewatch/IHttpBody.h"

#include <cpprest/json.h>

namespace io {
namespace tradewatch {
namespace client {
namespace model {

class  JsonBody
    : public IHttpBody
{
public:
    JsonBody( const web::json::value& value );
    virtual ~JsonBody();

    void writeTo( std::ostream& target ) override;

protected:
    web::json::value m_Json;
};

}
}
}
}

#endif /* IO_TRADEWATCH_CLIENT_MODEL_JsonBody_H_ */
